#! /bin/sh

for mon in $(bspc query -M); do
    bspc monitor $mon -r
done

for desktop in $(bspc query -D); do
    bspc desktop $desktop -r
done

for monitor in $(xrandr | grep " connected " | awk '{ print $1 }'); do
    bspc monitor $monitor \
   	 -n "$monitor" \
 	 -d {,,,,}
    let i++
done

nitrogen --restore &
sh $HOME/.config/polybar/launch.sh &

bspc subscribe monitor_geometry | head -1 # wait for resize event
sh $HOME/.bin/detect-monitors &
