#! /bin/sh

for monitor in $(xrandr | grep " connected " | awk '{ print $1 }'); do
    bspc monitor $monitor \
   	 -n "$monitor" \
 	 -d {,,,,}
done

nitrogen --restore &
sh $HOME/.config/polybar/launch.sh &

bspc subscribe monitor_geometry | head -1 # wait for resize event
sh $HOME/.bin/detect-monitors &
