#! /bin/sh
#Auto start

sxhkd &
feh --bg-fil ~/Imagens/Wallpapers/rick.png &
compton -b &
dunst &
pulseaudio --start &
xsetroot -cursor_name left_ptr &
export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &
dropbox &
megasync &
redshift &
xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
fc-cache -fv &
i3lock-wait-for-suspend &
srandrd autorandr --change --default &

#bspc monitor -d I II III IV V VI VII VIII IX X
# Setup monitors
for monitor in $(xrandr | grep " connected " | awk '{ print $1 }'); do
 	bspc monitor $monitor \
   	  -n "$monitor" \
 	    -d {,,,,}
 	let i++
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 button1
bspc config remove_disabled_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Telegram desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
