#! /bin/sh

for desktop in $(bspc query -D); do
	 bspc desktop $desktop -r
done

for monitor in $(xrandr | grep " connected " | awk '{ print $1 }'); do
 	bspc monitor $monitor \
   	  -n "$monitor" \
 	    -d {,,,,}
 	let i++
done

nitrogen --restore &
sh $HOME/.config/polybar/launch.sh &
